---
title: "Homework 01"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggforce)
library(ggridges)

```

# read data
```{r}
dat <- read_rds("../InfovisSS2021/datasets/lincoln_temps.rds")

```

## Visualisation of temperatures in Lincoln (Nebraska)

# 1. Ridgeline-Plot

```{r, code_folding: true, visualisation 1}
#Ridgeline-Plot

dat%>%
  ggplot(aes(x=mean_temp,y=month_long)) +
  geom_density_ridges(bandwidth=1, color="dark blue", fill="light blue") +
  labs(title="The month july has the highest mean temperature",subtitle="Temperatures in Lincoln (Nebraska)",caption="Temperature is measured in F°",x="Mean temperature per month",y=NULL)
```


#2. Violin-Plot
```{r, code_folding: true, visualisation 2}
#Violin-Plot

dat%>%
  ggplot(aes(x=month,y=mean_temp)) +
  geom_violin(color="dark blue", fill="light blue") +
  labs(title="The month july has the highest mean temperature",subtitle="Temperatures in Lincoln (Nebraska)",caption="Temperature is measured in F°",x=NULL,y="Mean temperature per month")
```

